(cl:in-package ds4_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          SQUARE-VAL
          SQUARE
          CROSS-VAL
          CROSS
          CIRCLE-VAL
          CIRCLE
          TRIANGLE-VAL
          TRIANGLE
          UP-VAL
          UP
          RIGHT-VAL
          RIGHT
          DOWN-VAL
          DOWN
          LEFT-VAL
          LEFT
          L1-VAL
          L1
          R1-VAL
          R1
          L2-VAL
          L2
          R2-VAL
          R2
          L3-VAL
          L3
          R3-VAL
          R3
          LEFT_X-VAL
          LEFT_X
          LEFT_Y-VAL
          LEFT_Y
          RIGHT_X-VAL
          RIGHT_X
          RIGHT_Y-VAL
          RIGHT_Y
          SHARE-VAL
          SHARE
          OPTION-VAL
          OPTION
          PS-VAL
          PS
          TOUCHPAD-VAL
          TOUCHPAD
          ACC_X-VAL
          ACC_X
          ACC_Y-VAL
          ACC_Y
          ACC_Z-VAL
          ACC_Z
          GYRO_ROL-VAL
          GYRO_ROL
          GYRO_PIT-VAL
          GYRO_PIT
          GYRO_YAW-VAL
          GYRO_YAW
          CONNECTED-VAL
          CONNECTED
))